// Banco de etiquetas virales para el generador de Nombre y Descripción.
// Versión en español. Misma estructura que viral-tags.js.
// Las competiciones, países, clubes y jugadores son nombres propios y se
// mantienen idénticos al archivo en inglés.
// Límite del campo de tags de YouTube: 500 chars (incl. comas + espacios).

export const VIRAL_TAGS = {
  // Etiquetas universales de fútbol — siempre se incluyen
  universal: [
    "futbol",
    "football",
    "soccer",
    "futebol",
    "quiz de futbol",
    "trivia de futbol",
    "reto de futbol",
    "desafio de futbol",
    "adivina el jugador",
    "adivina el equipo",
    "futbol quiz",
    "preguntas de futbol",
    "test de futbol",
    "fans del futbol",
    "amantes del futbol",
    "futbol iq",
    "conocimiento de futbol",
    "acertijo de futbol",
    "juego de futbol",
    "adivina al futbolista",
  ],

  // Etiquetas por tipo de quiz, según el tipo de runner
  quizType: {
    "team-by-nat": [
      "adivina el equipo",
      "adivina el equipo de futbol",
      "adivina el club",
      "adivina el equipo por nacionalidad",
      "adivina la alineacion",
      "adivina la alineacion de futbol",
      "quiz de alineaciones",
      "quiz de equipos",
      "quiz de clubes",
      "quiz de alineaciones de futbol",
      "quiz de equipos de futbol",
      "adivina el equipo por jugadores",
      "quiz de nacionalidades",
    ],
    "nat-by-club": [
      "adivina la seleccion",
      "adivina el pais",
      "adivina el pais por jugadores",
      "quiz de selecciones",
      "futbol internacional",
      "quiz de paises",
      "quiz del mundial",
      "quiz de la eurocopa",
      "quiz copa america",
      "alineacion de seleccion",
      "adivina la nacion",
    ],
    "career-path": [
      "adivina el jugador",
      "adivina el jugador por su carrera",
      "quiz de trayectoria",
      "adivina al futbolista por su carrera",
      "quiz de carrera del jugador",
      "carrera futbolistica",
      "adivina el jugador por sus clubes",
      "quiz de carrera",
      "historial de fichajes",
      "adivina la leyenda",
    ],
    "career-stats": [
      "adivina el jugador",
      "adivina el jugador por sus stats",
      "quiz de estadisticas",
      "adivina el jugador por sus goles",
      "quiz de stats",
      "estadisticas de futbol",
      "goles y asistencias",
      "adivina el delantero",
      "numeros de futbol",
    ],
    "four-params": [
      "adivina el jugador",
      "adivina el jugador por su club",
      "adivina el jugador por su posicion",
      "adivina el jugador por su pais",
      "adivina el jugador por su edad",
      "quiz de jugadores",
      "quiz de futbolistas",
      "adivina al futbolista",
      "adivina quien",
    ],
    "fake-info": [
      "adivina el dato falso",
      "encuentra la mentira",
      "verdadero o falso futbol",
      "detector de mentiras futbol",
      "encuentra el falso",
      "dato real o falso futbolista",
      "detecta el falso",
    ],
    "logo-name": [
      "adivina el equipo por el escudo",
      "escudos de futbol",
      "quiz de escudos de clubes",
      "quiz de insignias de futbol",
      "adivina la insignia",
      "adivina el escudo",
      "quiz de logos de futbol",
      "quiz de logos futbol",
    ],
    "player-name": [
      "adivina el nombre del jugador",
      "adivina el nombre del futbolista",
      "nombra al jugador",
      "di el nombre del jugador",
      "adivina quien es el jugador",
      "quiz de nombres de jugadores",
    ],
  },

  // Etiquetas de formato
  format: {
    regular: [
      "video quiz de futbol",
      "juego quiz de futbol",
      "reto quiz de futbol",
      "mejor quiz de futbol",
      "quiz de futbol mas dificil",
      "quiz de futbol hd",
    ],
    shorts: [
      "shorts",
      "futbol shorts",
      "shorts de futbol",
      "shorts virales",
      "youtube shorts",
      "quiz de futbol shorts",
      "shorts quiz futbol",
      "adivina el jugador shorts",
      "adivina el equipo shorts",
      "futbol tiktok",
      "shorts soccer",
      "shorts futbol",
      "shorts futbolero",
      "shorts virales de futbol",
      "shorts en tendencia",
    ],
  },

  // Etiquetas de liga / competición — idénticas al archivo en inglés (nombres propios)
  competition: {
    "premier league": ["premier league", "premier league quiz", "epl", "english football", "english premier league"],
    "la liga": ["la liga", "la liga quiz", "spanish football", "laliga"],
    "serie a": ["serie a", "serie a quiz", "italian football", "calcio"],
    bundesliga: ["bundesliga", "bundesliga quiz", "german football"],
    "ligue 1": ["ligue 1", "ligue 1 quiz", "french football"],
    "champions league": ["champions league", "ucl", "champions league quiz", "ucl quiz", "uefa champions league"],
    "europa league": ["europa league", "uel", "europa league quiz"],
    "world cup": ["world cup", "world cup quiz", "fifa world cup", "world cup 2026"],
    euro: ["euro", "euros", "uefa euro", "european championship"],
    "copa america": ["copa america", "copa america quiz", "south america football"],
    "africa cup": ["afcon", "africa cup of nations"],
    mls: ["mls", "major league soccer", "american soccer"],
    eredivisie: ["eredivisie", "dutch football"],
    "primeira liga": ["primeira liga", "portuguese football"],
    "saudi pro league": ["saudi pro league", "spl", "saudi arabia football"],
  },

  // Etiquetas de país
  country: {
    Spain: ["spain football", "españa", "spain national team"],
    England: ["england football", "three lions", "england national team"],
    Brazil: ["brazil football", "seleção", "brazil national team", "samba football"],
    Argentina: ["argentina football", "albiceleste", "argentina national team"],
    France: ["france football", "les bleus", "france national team"],
    Germany: ["germany football", "die mannschaft", "germany national team"],
    Italy: ["italy football", "azzurri", "italy national team"],
    Portugal: ["portugal football", "portugal national team"],
    Netherlands: ["netherlands football", "oranje", "netherlands national team"],
    Belgium: ["belgium football", "red devils belgium"],
    Croatia: ["croatia football", "croatia national team"],
    Morocco: ["morocco football", "atlas lions"],
    Mexico: ["mexico football", "el tri"],
    USA: ["usa football", "usmnt"],
    Japan: ["japan football", "samurai blue"],
    "South Korea": ["south korea football"],
    Egypt: ["egypt football", "pharaohs"],
    Nigeria: ["nigeria football", "super eagles"],
    Senegal: ["senegal football"],
    Uruguay: ["uruguay football"],
    Colombia: ["colombia football"],
    Chile: ["chile football"],
    Poland: ["poland football"],
    Norway: ["norway football"],
    Sweden: ["sweden football"],
    Denmark: ["denmark football"],
    Switzerland: ["switzerland football"],
    Turkey: ["turkey football"],
    Greece: ["greece football"],
    Russia: ["russia football"],
    Ukraine: ["ukraine football"],
    Ghana: ["ghana football"],
    "Cote d'Ivoire": ["ivory coast football"],
    Cameroon: ["cameroon football"],
    Algeria: ["algeria football"],
    Tunisia: ["tunisia football"],
    Australia: ["australia football", "socceroos"],
    Canada: ["canada football"],
    Ecuador: ["ecuador football"],
    Peru: ["peru football"],
  },

  // Etiquetas de clubes destacados — se incluyen si el club aparece en los niveles
  club: {
    "Real Madrid": ["real madrid", "real madrid quiz", "hala madrid", "los blancos"],
    Barcelona: ["barcelona", "fc barcelona", "barca", "fcb"],
    "Atletico Madrid": ["atletico madrid", "atleti"],
    "Manchester United": ["manchester united", "man united", "man utd", "mufc"],
    "Manchester City": ["manchester city", "man city", "mcfc"],
    Liverpool: ["liverpool", "lfc", "ynwa"],
    Chelsea: ["chelsea", "cfc", "chelsea fc"],
    Arsenal: ["arsenal", "afc", "gunners"],
    Tottenham: ["tottenham", "spurs", "thfc"],
    "Bayern Munich": ["bayern munich", "fc bayern", "bayern"],
    "Borussia Dortmund": ["borussia dortmund", "bvb", "dortmund"],
    Juventus: ["juventus", "juve", "bianconeri"],
    "AC Milan": ["ac milan", "milan", "rossoneri"],
    "Inter Milan": ["inter milan", "inter", "nerazzurri"],
    Napoli: ["napoli", "ssc napoli"],
    Roma: ["as roma", "roma"],
    PSG: ["psg", "paris saint germain", "paris"],
    Marseille: ["marseille", "om"],
    Ajax: ["ajax", "ajax amsterdam"],
    "PSV Eindhoven": ["psv", "psv eindhoven"],
    Benfica: ["benfica", "sl benfica"],
    Porto: ["porto", "fc porto"],
    "Sporting CP": ["sporting cp", "sporting lisbon"],
    "Al Nassr": ["al nassr", "alnassr"],
    "Al Hilal": ["al hilal", "alhilal"],
    "Inter Miami": ["inter miami", "inter miami quiz"],
  },

  // Etiquetas de jugadores destacados — se incluyen si el jugador aparece en las plantillas
  player: {
    Messi: ["messi", "leo messi", "lionel messi"],
    Ronaldo: ["ronaldo", "cristiano ronaldo", "cr7", "siuu"],
    Mbappe: ["mbappe", "kylian mbappe", "mbappé"],
    Haaland: ["haaland", "erling haaland"],
    Vinicius: ["vinicius", "vinicius junior", "vini jr"],
    Bellingham: ["bellingham", "jude bellingham"],
    Neymar: ["neymar", "neymar jr"],
    Salah: ["salah", "mohamed salah", "mo salah"],
    Lewandowski: ["lewandowski", "robert lewandowski"],
    Benzema: ["benzema", "karim benzema"],
    Modric: ["modric", "luka modric"],
    Kroos: ["kroos", "toni kroos"],
    Pedri: ["pedri"],
    Gavi: ["gavi"],
    Yamal: ["yamal", "lamine yamal"],
    Foden: ["foden", "phil foden"],
    Saka: ["saka", "bukayo saka"],
    Rodri: ["rodri"],
    Kane: ["kane", "harry kane"],
    Son: ["son heung min", "sonny"],
    "De Bruyne": ["de bruyne", "kdb", "kevin de bruyne"],
    Mahrez: ["mahrez", "riyad mahrez"],
    Griezmann: ["griezmann", "antoine griezmann"],
    Mane: ["mane", "sadio mane"],
    Iniesta: ["iniesta", "andres iniesta"],
    Xavi: ["xavi"],
    Pirlo: ["pirlo", "andrea pirlo"],
    Maldini: ["maldini", "paolo maldini"],
    Buffon: ["buffon", "gianluigi buffon"],
    Casillas: ["casillas", "iker casillas"],
    Pele: ["pele"],
    Maradona: ["maradona", "diego maradona"],
    Zidane: ["zidane", "zinedine zidane"],
    Ronaldinho: ["ronaldinho"],
    Ibrahimovic: ["ibrahimovic", "zlatan", "zlatan ibrahimovic"],
  },

  // Etiquetas de interacción / descubrimiento — términos de búsqueda de alto volumen
  engagement: [
    "viral",
    "en tendencia",
    "quiz divertido",
    "quiz dificil",
    "quiz imposible",
    "solo fans de verdad",
    "pon a prueba tu conocimiento",
    "fyp",
    "para ti",
    "mejor quiz",
    "quiz online",
    "quiz gratis",
    "quiz diario",
    "test para fans del futbol",
    "test de futbol iq",
    "cuantas aciertas",
  ],
};

/** Conveniencia: array plano de claves de competición para el matching. */
export const COMPETITION_KEYS = Object.keys(VIRAL_TAGS.competition);
export const COUNTRY_KEYS = Object.keys(VIRAL_TAGS.country);
export const CLUB_KEYS = Object.keys(VIRAL_TAGS.club);
export const PLAYER_KEYS = Object.keys(VIRAL_TAGS.player);
