// Viral-tag bank for the Name & Description generator.
// Tags are grouped so the generator can pick a viral mix per video.
// YouTube tag field cap: 500 chars (incl. commas + spaces).

export const VIRAL_TAGS = {
  // Universal football tags — always seeded in
  universal: [
    "football",
    "soccer",
    "futbol",
    "futebol",
    "football quiz",
    "soccer quiz",
    "football trivia",
    "soccer trivia",
    "football challenge",
    "soccer challenge",
    "football fans",
    "football lovers",
    "football iq",
    "soccer iq",
    "football knowledge",
    "football brain",
    "football puzzle",
    "football riddle",
    "football game",
    "guess the footballer",
  ],

  // Quiz-type tags keyed by runner kind
  quizType: {
    "team-by-nat": [
      "guess the team",
      "guess the football team",
      "guess the club",
      "guess the team by nationality",
      "guess the lineup",
      "guess the football lineup",
      "lineup quiz",
      "team quiz",
      "club quiz",
      "football lineup quiz",
      "football team quiz",
      "guess the team by players",
      "players nationality quiz",
    ],
    "nat-by-club": [
      "guess the national team",
      "guess the country",
      "guess the country by players",
      "national team quiz",
      "international football",
      "country quiz",
      "world cup quiz",
      "euro quiz",
      "copa america quiz",
      "national team lineup",
      "guess the nation",
    ],
    "career-path": [
      "guess the player",
      "guess the player by career",
      "career path quiz",
      "guess the footballer by career",
      "player career quiz",
      "football career",
      "guess the player by clubs",
      "career quiz",
      "transfer history",
      "guess the legend",
    ],
    "career-stats": [
      "guess the player",
      "guess the player by stats",
      "player stats quiz",
      "guess the player by goals",
      "stats quiz",
      "football stats",
      "goals and assists",
      "guess the striker",
      "football numbers",
    ],
    "four-params": [
      "guess the player",
      "guess the player by club",
      "guess the player by position",
      "guess the player by country",
      "guess the player by age",
      "player quiz",
      "footballer quiz",
      "guess the footballer",
      "guess who",
    ],
    "fake-info": [
      "guess the fake",
      "spot the lie",
      "true or false football",
      "football lie detector",
      "find the fake",
      "footballer fact or fake",
      "spot the fake",
    ],
    "logo-name": [
      "guess the team by logo",
      "football logos",
      "club logo quiz",
      "football badge quiz",
      "guess the badge",
      "guess the crest",
      "soccer logo quiz",
      "logo quiz football",
    ],
    "player-name": [
      "guess the player name",
      "guess the footballer name",
      "name the player",
      "name that player",
      "guess who the player is",
      "player name quiz",
    ],
  },

  // Format tags
  format: {
    regular: [
      "football quiz video",
      "football quiz game",
      "football quiz challenge",
      "best football quiz",
      "hardest football quiz",
      "football quiz hd",
    ],
    shorts: [
      "shorts",
      "football shorts",
      "soccer shorts",
      "viral shorts",
      "youtube shorts",
      "football quiz shorts",
      "soccer quiz shorts",
      "guess the player shorts",
      "guess the team shorts",
      "football tiktok",
      "soccer tiktok",
      "shorts football",
      "shorts soccer",
      "viral football shorts",
      "trending shorts",
    ],
  },

  // League / competition tags — picked when the actual levels feature these
  competition: {
    "premier league": ["premier league", "premier league quiz", "epl", "english football", "english premier league"],
    "la liga": ["la liga", "la liga quiz", "spanish football", "laliga"],
    "serie a": ["serie a", "serie a quiz", "italian football", "calcio"],
    bundesliga: ["bundesliga", "bundesliga quiz", "german football"],
    "ligue 1": ["ligue 1", "ligue 1 quiz", "french football"],
    "champions league": ["champions league", "ucl", "champions league quiz", "ucl quiz", "uefa champions league"],
    "europa league": ["europa league", "uel", "europa league quiz"],
    "world cup": ["world cup", "world cup quiz", "fifa world cup", "world cup 2026"],
    euro: ["euro", "euros", "uefa euro", "european championship"],
    "copa america": ["copa america", "copa america quiz", "south america football"],
    "africa cup": ["afcon", "africa cup of nations"],
    mls: ["mls", "major league soccer", "american soccer"],
    eredivisie: ["eredivisie", "dutch football"],
    "primeira liga": ["primeira liga", "portuguese football"],
    "saudi pro league": ["saudi pro league", "spl", "saudi arabia football"],
  },

  // Country tags
  country: {
    Spain: ["spain football", "españa", "spain national team"],
    England: ["england football", "three lions", "england national team"],
    Brazil: ["brazil football", "seleção", "brazil national team", "samba football"],
    Argentina: ["argentina football", "albiceleste", "argentina national team"],
    France: ["france football", "les bleus", "france national team"],
    Germany: ["germany football", "die mannschaft", "germany national team"],
    Italy: ["italy football", "azzurri", "italy national team"],
    Portugal: ["portugal football", "portugal national team"],
    Netherlands: ["netherlands football", "oranje", "netherlands national team"],
    Belgium: ["belgium football", "red devils belgium"],
    Croatia: ["croatia football", "croatia national team"],
    Morocco: ["morocco football", "atlas lions"],
    Mexico: ["mexico football", "el tri"],
    USA: ["usa football", "usmnt"],
    Japan: ["japan football", "samurai blue"],
    "South Korea": ["south korea football"],
    Egypt: ["egypt football", "pharaohs"],
    Nigeria: ["nigeria football", "super eagles"],
    Senegal: ["senegal football"],
    Uruguay: ["uruguay football"],
    Colombia: ["colombia football"],
    Chile: ["chile football"],
    Poland: ["poland football"],
    Norway: ["norway football"],
    Sweden: ["sweden football"],
    Denmark: ["denmark football"],
    Switzerland: ["switzerland football"],
    Turkey: ["turkey football"],
    Greece: ["greece football"],
    Russia: ["russia football"],
    Ukraine: ["ukraine football"],
    Ghana: ["ghana football"],
    "Cote d'Ivoire": ["ivory coast football"],
    Cameroon: ["cameroon football"],
    Algeria: ["algeria football"],
    Tunisia: ["tunisia football"],
    Australia: ["australia football", "socceroos"],
    Canada: ["canada football"],
    Ecuador: ["ecuador football"],
    Peru: ["peru football"],
  },

  // Marquee club tags - matched if a club appears in the levels
  club: {
    "Real Madrid": ["real madrid", "real madrid quiz", "hala madrid", "los blancos"],
    Barcelona: ["barcelona", "fc barcelona", "barca", "fcb"],
    "Atletico Madrid": ["atletico madrid", "atleti"],
    "Manchester United": ["manchester united", "man united", "man utd", "mufc"],
    "Manchester City": ["manchester city", "man city", "mcfc"],
    Liverpool: ["liverpool", "lfc", "ynwa"],
    Chelsea: ["chelsea", "cfc", "chelsea fc"],
    Arsenal: ["arsenal", "afc", "gunners"],
    Tottenham: ["tottenham", "spurs", "thfc"],
    "Bayern Munich": ["bayern munich", "fc bayern", "bayern"],
    "Borussia Dortmund": ["borussia dortmund", "bvb", "dortmund"],
    Juventus: ["juventus", "juve", "bianconeri"],
    "AC Milan": ["ac milan", "milan", "rossoneri"],
    "Inter Milan": ["inter milan", "inter", "nerazzurri"],
    Napoli: ["napoli", "ssc napoli"],
    Roma: ["as roma", "roma"],
    PSG: ["psg", "paris saint germain", "paris"],
    Marseille: ["marseille", "om"],
    Ajax: ["ajax", "ajax amsterdam"],
    "PSV Eindhoven": ["psv", "psv eindhoven"],
    Benfica: ["benfica", "sl benfica"],
    Porto: ["porto", "fc porto"],
    "Sporting CP": ["sporting cp", "sporting lisbon"],
    "Al Nassr": ["al nassr", "alnassr"],
    "Al Hilal": ["al hilal", "alhilal"],
    "Inter Miami": ["inter miami", "inter miami quiz"],
  },

  // Marquee player tags — matched if a player appears in the current squads
  player: {
    Messi: ["messi", "leo messi", "lionel messi"],
    Ronaldo: ["ronaldo", "cristiano ronaldo", "cr7", "siuu"],
    Mbappe: ["mbappe", "kylian mbappe", "mbappé"],
    Haaland: ["haaland", "erling haaland"],
    Vinicius: ["vinicius", "vinicius junior", "vini jr"],
    Bellingham: ["bellingham", "jude bellingham"],
    Neymar: ["neymar", "neymar jr"],
    Salah: ["salah", "mohamed salah", "mo salah"],
    Lewandowski: ["lewandowski", "robert lewandowski"],
    Benzema: ["benzema", "karim benzema"],
    Modric: ["modric", "luka modric"],
    Kroos: ["kroos", "toni kroos"],
    Pedri: ["pedri"],
    Gavi: ["gavi"],
    Yamal: ["yamal", "lamine yamal"],
    Foden: ["foden", "phil foden"],
    Saka: ["saka", "bukayo saka"],
    Rodri: ["rodri"],
    Kane: ["kane", "harry kane"],
    Son: ["son heung min", "sonny"],
    "De Bruyne": ["de bruyne", "kdb", "kevin de bruyne"],
    Mahrez: ["mahrez", "riyad mahrez"],
    Griezmann: ["griezmann", "antoine griezmann"],
    Mane: ["mane", "sadio mane"],
    Iniesta: ["iniesta", "andres iniesta"],
    Xavi: ["xavi"],
    Pirlo: ["pirlo", "andrea pirlo"],
    Maldini: ["maldini", "paolo maldini"],
    Buffon: ["buffon", "gianluigi buffon"],
    Casillas: ["casillas", "iker casillas"],
    Pele: ["pele"],
    Maradona: ["maradona", "diego maradona"],
    Zidane: ["zidane", "zinedine zidane"],
    Ronaldinho: ["ronaldinho"],
    Ibrahimovic: ["ibrahimovic", "zlatan", "zlatan ibrahimovic"],
  },

  // Engagement / discovery tags - high-volume search terms
  engagement: [
    "viral",
    "trending",
    "fun quiz",
    "hard quiz",
    "impossible quiz",
    "only true fans",
    "test your knowledge",
    "fyp",
    "for you page",
    "best quiz",
    "online quiz",
    "free quiz",
    "daily quiz",
    "football fan test",
    "football iq test",
    "how many can you get",
  ],
};

/** Convenience: flat array of competition keys for matching. */
export const COMPETITION_KEYS = Object.keys(VIRAL_TAGS.competition);
export const COUNTRY_KEYS = Object.keys(VIRAL_TAGS.country);
export const CLUB_KEYS = Object.keys(VIRAL_TAGS.club);
export const PLAYER_KEYS = Object.keys(VIRAL_TAGS.player);
